services:
#    gallery.example:
#        class: GalleryBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
   admin.photo:
        class: GalleryBundle\Admin\PhotoAdmin
        arguments: [~, GalleryBundle\Entity\Photo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Photos, group: Фотографии }
