<?php

namespace AppBundle\Repository;

/**
 * NewsnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsnRepository extends \Doctrine\ORM\EntityRepository
{
}
