# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
services:
    # ...
    admin.newsn:
        class: AppBundle\Admin\NewsnAdmin
        arguments: [~, AppBundle\Entity\Newsn, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: News, group: Новости }



    
